### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by andomort** [M-Tass/Cyth#1]
Lots of errors upon building. (Total of 154).
Before building, only 2 errors which are below.
[https://gyazo.com/fcd353b65329888d3dc5d02a721db12e](url)

**Comment by M-Tass** [comment]
Hello,
[For the first two errors, uncomment these lines](https://github.com/ocornut/imgui/blob/83d97d4a9b8c4a7129bb6132500cb9f7442a373e/examples/directx9_example/imgui_impl_dx9.h#L25-L27)
And as for the rest of the 154 errors, I wouldn't know where to start unless you post a screenshot however if I were to take a guess I'd say that it's mostly sfinae errors meaning you don't have VS2017

**Comment by ghost** [comment]
the issue is you need to redownload imgui or download the git repo with the recursive flag in the git clone params

**Comment by andomort** [comment]
@M-Tass 
I've uncommented the lines, and the 2 errors are still persisting.
https://i.gyazo.com/c841ef0f11249f0acdd34bb5c1d05f5c.png
https://i.gyazo.com/9010b1368fded81fde233039b07503d7.png
https://i.gyazo.com/490ca737de8d5b07fadd45e494107be4.png
https://i.gyazo.com/ea4e1b645567a7d7bd2e2f051d8e28c7.png
https://i.gyazo.com/db25eaa8c6458463731b2adf30989caf.png

**Comment by M-Tass** [comment]
Hello,
Sorry I didn't realize that Imgui was updated with drastic API changes, thus I've uploaded the imgui files which I used to compile the pe

**Comment by andomort** [comment]
Thank you, I appreciate it!
