### ISSUE TITLE
ESP isn't being drawn properly onto players, unless the escape menu is open?

### ISSUE THREAD

**Issue by HOTD** [M-Tass/Cyth#10]
Title. ESP positions are off but when you open the pause menu, they are corrected to the right positions.

**Comment by M-Tass** [comment]
Hello,

Can you please post a video showing this issue?
I can't seem to replicate it on my end

**Comment by HOTD** [comment]
Sorry for the late reply, haven't been playing gmod a lot. The ESP seems to acting strange with or without the escape menu, seems to be rendering in the wrong positions (trying to find my screenshots of this) or not rendering at all. When you open the escape menu it fixes it (https://i.imgur.com/q3aFP4G.png). 

Here's a video: https://www.youtube.com/watch?v=FnJxVdYeVRw

**Comment by HOTD** [comment]
Here's the video of the boxes rendered in the wrong areas: https://www.youtube.com/watch?v=08i1xmCqg4I

**Comment by M-Tass** [comment]
Does replacing `esp::draw_bounding_box` with `esp::draw_3d_box` fix the issue?

**Comment by HOTD** [comment]
Nope, https://www.youtube.com/watch?v=eGgDOz4fWII. I do like the 3D boxes though.

**Comment by M-Tass** [comment]
Looks like an issue with the view matrix.
Can you post the server IP?

**Comment by HOTD** [comment]
92.60.12.133:27015 or 92.60.12.133:10000 . Zombie.Zone ZS Server 1 & 2

**Comment by HOTD** [comment]
Edit: Still having issue on that zs server. I'm out of ideas.

**Comment by xbRead** [comment]
Try rendering from FocusOverlayPanel havent reversed or done anything to gmod usually on csgo section.

**Comment by FocuzJS** [comment]
I've ran into this now aswell, its a server addon type thing it seems

**Comment by FocuzJS** [comment]
can confirm it's a view matrix issue, player locations are correct for my aimbot

**Comment by M-Tass** [comment]
Can you check if cam.Start3D fixes the issues?

**Comment by FocuzJS** [comment]
I was thinking of getting the view matrix another way, and seeing if https://wiki.garrysmod.com/page/Entity/GetWorldTransformMatrix is a different vmatrix than `globals::engine->get_view_matrix()`

how would cam.Start3D help, it's lua aswell right?

**Comment by M-Tass** [comment]
[GetWorldTransformMatrix](https://wiki.garrysmod.com/page/Entity/GetWorldTransformMatrix) isn't the view matrix rather the rgfl_CoordinateFrame

If I'm not mistaken cam.Start3D seems as if it calls CViewRender::SetupMain3DView (Which re-calculates the view matrix and caches it)

**Comment by FocuzJS** [comment]
[cam.Start3D](https://wiki.garrysmod.com/page/cam/Start3D) says it expects cam.End3D to be called. Should this be called directly after since im guessing the cache will be updated or on an event hook?
and how often do you think this call should be made, once per run or as part of get_view_matrix?

**Comment by M-Tass** [comment]
See if this works:

```c++
cam.Start3D(LocalPlayer():EyePos(), LocalPlayer():EyeAngles(), ...)
auto& matrix = globals::engine->get_view_matrix()

// ESP rendering

cam.End3D()
```

**Comment by M-Tass** [comment]
Using `cam.Start3D` does indeed solve the issue

**Source**
--
```c++
if (auto glua = Lua::get())
{
	auto& [x, y] = ImGui::GetIO().DisplaySize;

	glua->push_special(Lua::special::glob);
	glua->get_field(-1, "LocalPlayer");
	glua->call(0, 1);

	glua->get_field(-1, "EyePos");
	glua->push(-2);
	glua->call(1, 1);

	glua->get_field(-2, "EyeAngles");
	glua->push(-3);
	glua->call(1, 1);

	glua->get_field(-4, "cam");
	glua->get_field(-1, "Start3D");
	glua->push(-4);
	glua->push(-4);
	glua->push_nil();
	glua->push_number(0.);
	glua->push_number(0.);
	glua->push_number(x);
	glua->push_number(y);
	glua->push_nil();
	glua->push_nil();
	glua->call(9, 0);

	glua->pop(5);

	// Rendering / ESP here

	glua->push_special(Lua::special::glob);
	glua->get_field(-1, "cam");
	glua->get_field(-1, "End3D");
	glua->call(0, 0);
	glua->pop(2);
}
```

**Comment by FocuzJS** [comment]
yes it works for me aswell. [Start3D](https://wiki.garrysmod.com/page/cam/Start3D) has defaults defined so passing it tables is not necessary. I was able to get this working with few simple lines wrapped around get_view_matrix since i suspected it was the only issue.
my fix thanks to your tip:
```cpp
    auto glua = globals::lua->create_interface(lua::type::client);

    if (glua) {
        glua->PushSpecial(lua::special::glob);
        glua->GetField(-1, "cam");
        glua->GetField(-1, "Start3D");
        glua->Call(0, 1);
        glua->Pop();
    }
    auto& matrix = globals::engine->get_view_matrix();
    if (glua) {
        glua->GetField(-1, "End3D");
        glua->Call(0, 1);
        glua->Pop(3);
    }
```
and then render esp normally so in my case, i don't have multiple lua contexts open at once! thanks for the quick responses.

**Comment by M-Tass** [comment]
Interesting. I thought 
Anyways, nice work!

**Comment by M-Tass** [comment]
Sorry, I mistakenly closed this issue. Opening it again
If the issue is resolved on @HOTD's end, they may close it

**Comment by FocuzJS** [comment]
![hl2_2018-07-08_09-48-39](https://user-images.githubusercontent.com/16075058/42420455-31cbaf98-8294-11e8-9912-078e01a526eb.jpg)
just tested on the servers he had trouble with before. everything looks good to me

**Comment by xbread** [comment]
@FocuzJS you got a discord that i can message you on?

**Comment by FocuzJS** [comment]
@xbRead post yours i'll add you

**Comment by xbRead** [comment]
✘Bread#0105 @FocuzJS

**Comment by HOTD** [comment]
Seems to work. Closing.
