### ISSUE TITLE
Weapon ESP

### ISSUE THREAD

**Issue by xbread** [M-Tass/Cyth#13]
While making weapon esp I saw that garry's mod hl2 weapons look ugly, I was wondering if there was a way to filter out #HL2_  (I know theres a way) but how would I go about doing it 
![unknown](https://user-images.githubusercontent.com/25601465/42425025-6476f7c2-82e4-11e8-9aea-6a1bbae31efe.png)

**Comment by M-Tass** [comment]
Hi,
You can either use [language.GetPhrase](https://wiki.garrysmod.com/page/language/GetPhrase) or [ILocalize::FindAsUTF8](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/tier1/ilocalize.h#L81)

If you're going for the latter:
```c++
class Localize
{
public:
	FORCE_INLINE char* find(const char* name)
	{
		return METHOD(15, Localize::find)(name);
	}
};

namespace globals
{
	inline Localize* localize = nullptr;
}
```

Interface name is `VGUI_Localize005` located in `vgui2.dll`

**Comment by FocuzJS** [comment]
@M-Tass in his screenshot, is that what `GetPrintName` returns for hl2 guns?

**Comment by FocuzJS** [comment]
@M-Tass how do you know the source sdk so well with indexes too?! :)

**Comment by M-Tass** [comment]
I'm just that good *wink wink\*
Anyway, yes, that's the return of `GetPrintName` for HL2 weapons
