### ISSUE TITLE
Players in vehicles show incorrect world position of boxes for that player

### ISSUE THREAD

**Issue by FocuzJS** [M-Tass/Cyth#17]
Title says it all, players boxes on screen are supper bugged when **THEY** are inside a vehicle, I haven't tested in sandbox but i doubt it's vcmod.

When I created my own extensions to this cheat such as player aimbot and some other things like player eye angle line drawn when an m9k_ gun out, but my locations are correct still while player in vehicle.

I understand that the wallhack isn't lua and resolves it's locations/angles differently than i did, and i was wondering if you knew the cause for this weird bug before i overhauled the cheat with more lua.

I can post screenshot if you'd like to see what I mean.

**Comment by M-Tass** [comment]
Oh dear, it appears the m_rgflCoordinate frame is messing up again. Switching to [3D boxes](https://github.com/M-Tass/Cyth/blob/7d61be41187928b1853949006f335733c890887e/Esp.hpp#L170) should fix the issue

**Comment by FocuzJS** [comment]
Gotcha! I'm going to try and switch 2d to use the same calcs 👍  thanks

**Comment by FocuzJS** [comment]
thanks for the tip! although the `get_pos()` function wasn't correct while they were `InVehicle`, I just replaced it with a `GetPos` lua equivalent for position and normal bounding boxes when they aren't in vehicle (for performance) and its working great
