### ISSUE TITLE
Issue making somewhat advanced lua calls

### ISSUE THREAD

**Issue by FocuzJS** [M-Tass/Cyth#6]
So I understand this code:
```cpp
inline std::string get_name()
	{
		auto glua = globals::lua->create_interface(lua::type::client);

		if (!glua)
			return {};

		glua->PushSpecial(lua::special::glob);
		glua->GetField(-1, "Entity");
		glua->PushNumber(this->get_index());
		glua->Call(1, 1);

		glua->GetField(-1, "Nick");
		glua->Push(-2);
		glua->Call(1, 1);

		std::string name = glua->GetString();
		glua->Pop(3);

		return name;
	}
```

but when i want to chain together some calls, for example:

```cpp
inline std::string get_active_weap_name()
	{
		auto glua = globals::lua->create_interface(lua::type::client);

		if (!glua)
			return {};

		glua->PushSpecial(lua::special::glob);
		glua->GetField(-1, "Entity");
		glua->PushNumber(this->get_index());
		glua->Call(1, 1);

		glua->GetField(-1, "GetActiveWeapon");
		glua->Push(-2);
		glua->Call(1, 1);

		glua->GetField(-1, "GetClass");
		glua->Push(-2);
		glua->Call(1, 1);

		std::string name = glua->GetString();
		glua->Pop(3);

		return name;
	}
```

for a lua call would be `Entity( 1 ):GetActiveWeapon():GetClass()`

any help understanding or just a solution would be greatly appreciated

**Comment by M-Tass** [comment]
Hello,

You forgot to pop off the ActiveWeapon entity :)
Simply change the `glua->Pop(3)` to `glua->Pop(4)`

Here's an approximation of what the lua stack looks like:

---
**Command(s):**

`glua->PushSpecial(glob);`

**Stack state after executing the above command(s)**:
1.  GLOB
---
**Command(s):**
```
glua->GetField(-1, "Entity");
...
glua->GetField(-1, "GetActiveWeapon");
...
glua->Call(1, 1);
```
**Stack state after executing the above command(s)**:
1. ActiveWeapon
2. Entity table
3. GLOB
---
**Command(s):**
```
glua->GetField(-1, "GetClass");
...
glua->Call(1, 1);
```
**Stack state after executing the above command(s)**:
1. Classname
2. ActiveWeapon
3. Entity table
4. GLOB

**Comment by FocuzJS** [comment]
I'm a bit confused where the `glua->Push(-2)` comes into play.

```cpp
inline std::string get_active_weap_name()
	{
		auto glua = globals::lua->create_interface(lua::type::client);

		if (!glua)
			return {};

		glua->PushSpecial(lua::special::glob);
		glua->GetField(-1, "Entity");
		glua->PushNumber(this->get_index());
		glua->Call(1, 1);

		glua->GetField(-1, "GetActiveWeapon");
		glua->Call(1, 1);

		glua->GetField(-1, "GetClass");
		glua->Call(1, 1);

		std::string name = glua->GetString();
		glua->Pop(4);

		return name;
	}
```
with that I get, attempted to call a userdata value.

I assume it needs a `glua->Push(-2)` in between GetActiveWeapon and the call, but when trying the same tactic with putting `glua->Push(-2)` in between GetClass and Call, I still do not get the desired result. Can you please help clarify what must be in the ... section of your example.

Another thing that's bothering me is i can successfully call GetClass on the Entity and it returns `player` but i just want to get activeweapon and getclass of that obviously and it seems to be quite a different operation than making one call

**Comment by FocuzJS** [comment]
and trust me i really want to figure this out, i've probably crashed my game trying little changes at least 40 times in the past 24 hours

**Comment by FocuzJS** [comment]
Okay so I've got it working now, but it crashes after about 5 full seconds with a tried to use NULL entity.

```cpp
	inline std::string get_active_weap_name()
	{
		auto glua = globals::lua->create_interface(lua::type::client);

		if (!glua)
			return {};

		glua->PushSpecial(lua::special::glob);
		glua->GetField(-1, "Entity");
		glua->PushNumber(this->get_index());
		glua->Call(1, 1);

		glua->GetField(-1, "GetActiveWeapon");
		glua->Push(-2);
		glua->Call(1, 1);

		glua->GetField(-2, "GetClass");
		glua->Push(-2);
		glua->Call(1, 1);

		std::string name = glua->GetString();
		glua->Pop(4);

		return name;
	}
```

that's what I've got. Am I not popping enough off the stack?

**Comment by FocuzJS** [comment]
So im thinking a null check somewhere might fix it?

**Comment by M-Tass** [comment]
Run the function only if the player is alive. GetActiveWeapon typically results in a NULL entity if the player is dead causing the subsequent call to GetClass to fail and hence crash the game

**Comment by FocuzJS** [comment]
You sir, are a garry's mod genius! amazing job helping me out, simple alive check and we are in business! You've also done wonders helping me to understand how to efficiently use the stack, and for that I thank you very much

**Comment by FocuzJS** [comment]
After about 20 minutes of play, I get another trying to use null entity and i'm performing `Alive` checks and `IsValid`, is there some way to check and see if the entity on the stack is NULL before trying to use it rather than using lua checks that are failing

**Comment by M-Tass** [comment]
Hi,
Sorry for the delayed response

The error comes from GetActiveWeapon returning a NULL entity (probably due to SWEP's in this case)

I just tested the following code on two seperate servers and it works perfectly:
```
auto& matrix = engine->get_view_matrix();

for (size_t i = 1, local = engine->get_local_player(); i <= engine->get_max_clients(); ++i)
{
	auto player = entities->get_entity(i);

	if
	(
		!player				// Is the player valid? 
		|| player->is_dormant()		// Is the player information outdated?
		|| player->get_health() < 1     // Is the player dead? m_lifeState is a better variable to check as you can have 0 health and still be alive
		|| i == local			// Is it us?
	)
		continue;

	auto glua = globals::lua->create_interface(lua::type::client);

	if (!glua)
		return;

	glua->PushSpecial(lua::special::glob);
	glua->GetField(-1, "Entity");
	glua->PushNumber(i);
	glua->Call(1, 1);

	glua->GetField(-1, "GetActiveWeapon");
	glua->Push(-2);
	glua->Call(1, 1);

	glua->GetField(-1, "IsValid");
	glua->Push(-2);
	glua->Call(1, 1);

	if (!glua->GetBool())
	{
		// ActiveWeapon was nullptr / NULL
		glua->Pop(4);
		continue;
	}

	// Weapon is valid. Pop the IsValid check off the stack
	glua->Pop();

	glua->GetField(-1, "GetClass");
	glua->Push(-2);
	glua->Call(1, 1);

	std::string name = glua->GetString();
	glua->Pop(4);

	if (auto pos = esp::transform(matrix, player->get_abs_origin()))
	{
		esp::draw_text(pos.value(), IM_COL32(255, 0, 0, 255), name);
	}
}

```

Hope it helps!

**Comment by FocuzJS** [comment]
I was foolishly associating the Entity call with the null entity error, therefore i was using `IsValid` on it instead of `GetActiveWeapon`.. Silly me, thanks for the quick response!
