### ISSUE TITLE
Signatures outdated

### ISSUE THREAD

**Issue by FocuzJS** [M-Tass/Cyth#7]
I'd love to contribute to this somehow but i've never used IDA, but title says it all. There was just a May 2018 update that broke sigs 🔢 :/

**Comment by M-Tass** [comment]
Hi,
Which signatures are broken?

**Comment by FocuzJS** [comment]
Actually upon further inspection, im not sure if it's actually a sig issue. Can you confirm if everything still works for you?

**Comment by M-Tass** [comment]
Everything is working fine on my end

**Comment by FocuzJS** [comment]
After trying everything i could think of, I believe the steam overlay was glitching out and making it seem broken; when i tested some debugging by using the console hooks to print some stuff using the glua hooks, it worked.

UPDATE:
I rebooted and everything is good.... -_-
