### ISSUE TITLE
Safe to call functions that set stuff?

### ISSUE THREAD

**Issue by FocuzJS** [M-Tass/Cyth#9]
I'm about to try to make a linear path regression aimbot and thought I'd ask if there was any stipulation on using functions that set things as such they may more easily trigger detection vectors. I believe it will be fine. But worst case, angles can be written other ways I suppose.

[Function in question](https://wiki.garrysmod.com/page/Player/SetEyeAngles)

**Comment by M-Tass** [comment]
It's hard to say but I guess under 95% of the circumstances, it's safe
Alternatively you can just call `engine->SetViewAngles` (Clientside `player.SetEyeAngles` is just a wrapper around `engine->SetViewAngles`)

**Comment by FocuzJS** [comment]
Could you give a quick rundown on how to use glua `CreateTable` / `SetTable` to make an x,y,z vector able to be pushed into `SetEyeTarget`

**Comment by M-Tass** [comment]
Call the [Vector](https://wiki.garrysmod.com/page/Global/Vector) function
```c++
glua->get_field(-1, "Vector");
glua->push_number(0.);
glua->push_number(0.);
glua->push_number(0.);
glua->call(3, 1);
```

**Comment by FocuzJS** [comment]
Since I'm about to be calling a lot of functions that need passed arguments, I'm just wondering about this: (the `glua->Push(-2);` to be exact)
```cpp
inline std::string get_group_name()
	{
		auto glua = globals::lua->create_interface(lua::type::client);

		if (!glua)
			return {};

		glua->PushSpecial(lua::special::glob);
		glua->GetField(-1, "Entity");
		glua->PushNumber(this->get_index());
		glua->Call(1, 1);

		glua->GetField(-1, "GetUserGroup");
		glua->Push(-2); // right here I'm wondering 
                // GetUserGroup doesn't take any args but it does return
		glua->Call(1, 1); // yet we call with 1 arg and 1 return val

		std::string name = glua->GetString();
		glua->Pop(3);
		return name;
	}
```

so say if `Entity:GetUserGroup()` took 1 string argument
would I need to `push(-2)` and `push_string` then `call(2, 1)` or what? Hopefully my question is clear.

**Comment by M-Tass** [comment]
Yes. The first argument of a member function is always the target object

**Comment by FocuzJS** [comment]
Okay sick, so lua normally just handles this for us for simplicity?

**Comment by M-Tass** [comment]
Yes, just like C++

**Comment by FocuzJS** [comment]
https://wiki.garrysmod.com/page/util/TraceLine I think I need to make my own table on the stack to call this. I'm wanting to use traceline for a visibility check.
here's the concept:
```lua
function PlayerVisible( ply, testpos )
	if !ply:IsValid() or !ply:IsPlayer() then return false end

	local td = {start = LocalPlayer():GetShootPos(), endpos = testpos, filter = {LocalPlayer(), ply}, mask = MASK_SHOT}
	local tr = util.TraceLine(td)

	--if tr.Entity:IsValid() and tr.Entity == ply then return true end
	if !tr.Hit then return true end
	return false

end
```

**Comment by FocuzJS** [comment]
assuming it's 
```cpp
glua->CreateTable();
glua->SetField(-1, "test");
glua->PushString("test1");
glua->SetTable(-3)
```

UPDATE:
```cpp
glua->CreateTable();

glua->PushNumber(0);
glua->SetField(-2, "x");
glua->PushNumber(0);
glua->SetField(-2, "y");
glua->PushNumber(0);
glua->SetField(-2, "z");
```
this worked, is this good?

**Comment by FocuzJS** [comment]
Thanks again for all the help, without good documentation getting started was hard but you've made this learning curve much easier. I've done quite a bit of lua porting now, but I thought you might be proud of how well I figured out this one specifically.

```cpp
inline bool is_player_visible(Player* us, Vector endPos) {
	auto glua = globals::lua->create_interface(lua::type::client);

	if (!glua)
		return {};

	glua->PushSpecial(lua::special::glob);
	glua->GetField(-1, "MASK_SHOT");
	auto mask = glua->GetNumber();
	glua->Pop();

	glua->GetField(-1, "Entity");
	glua->PushNumber(this->get_index());
	glua->Call(1, 1); // targetEntity

	glua->GetField(-2, "Entity");
	glua->PushNumber(us->get_index());
	glua->Call(1, 1); // ourEntity

	Vector startPos = us->get_view_pos();

	glua->GetField(-3, "Vector"); // -3 glob
	glua->PushNumber(startPos.at(0));
	glua->PushNumber(startPos.at(1));
	glua->PushNumber(startPos.at(2));
	glua->Call(3, 1); // startVector

	glua->GetField(-4, "Vector"); // -3 glob
	glua->PushNumber(endPos.at(0));
	glua->PushNumber(endPos.at(1));
	glua->PushNumber(endPos.at(2));
	glua->Call(3, 1); // endVector

	glua->CreateTable(); // filterTable

	glua->PushNumber(1);
	glua->Push(-5); // ourEntity
	glua->SetTable(-3);

	glua->PushNumber(2);
	glua->Push(-6); //targetEntity
	glua->SetTable(-3);


	glua->CreateTable(); //traceTable

	glua->Push(-4);// startPos
	glua->SetField(-2, "start");
	glua->Push(-3); // endPos
	glua->SetField(-2, "endpos");
	glua->Push(-2); // filterTable
	glua->SetField(-2, "filter");
	glua->PushNumber(mask);
	glua->SetField(-2, "mask");

	glua->GetField(-7, "util"); // util
	glua->GetField(-1, "TraceLine");
	glua->Push(-3);
	glua->Call(1, 1); //traceResultTable

	glua->PushString("Hit");
	glua->GetTable(-2);
	auto hit = glua->GetBool(-1);
	glua->Pop(10);

	return !hit;
}
```

**Comment by FocuzJS** [comment]
I have a playermodel where his head position is under his feat, it's the OpFor playermodel https://steamcommunity.com/sharedfiles/filedetails/?id=176238701 what would you recommend, just adding to the vertical component of the vector to level it out for that model or is there a better way?

**Comment by FocuzJS** [comment]
this was due to the way i was initially using GetAttachment("eyes") for a better head position, i've since switched to adaptive bone switching with visibility checks and everything is working well!

**Comment by M-Tass** [comment]
Very nice!
